# Generated by Django 4.2.16 on 2024-12-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='botapp.message'),
            preserve_default=False,
        ),
    ]
