# Generated by Django 5.1.5 on 2025-01-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='source_documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
