# Generated by Django 5.1.5 on 2025-01-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_message_response_message_source_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot_response',
            field=models.BooleanField(default=False),
        ),
    ]
